Course controllers
EVinokurov/Courses pull request #1
Opened 2019-04-21 14:15 UTC by SUDPro

Сделал раздел курсов(удаление,создание, редактирование), кроме фильтров, исправил загрузку файлов при редактировании, исправил загрузку файлов при создании.

2019-04-22 16:25 UTC, RobertGareev requested changes

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
>      FileService fileService;
Автоварить поля - плохая практика. 
Либо через конструктор, либо через сеттеры
READ: https://habr.com/ru/post/334636/

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
> +        model.addAttribute("course", courseService.getCourseById(id));
Строковые константы следует выносить в public static final string поля (особенно если неск раз юзаются у вас) #ящитаю

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
> +        modelMap.addAttribute("time", courseService.getCourseById(id).getDeadline().toString().split(" ")[0]);
Почему второй раз вызываешь courseService.getCourseById(id)?
Следует вынести в переменную

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
> +        return "redact";
redact?))0

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
> +
лишняя строка

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
> +    public String updateCourse(@PathVariable("id") long id, Course course, @RequestParam(value = "file", required = false) MultipartFile file) {
Слишком длинная строка, следует разбить на несколько

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
> +    public String deleteCourse(@RequestParam(value = "id", required = false) long id) {
required = false ? без айдишника удалять будешь?

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
> +
удали сразу везде, где увидишь

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
>      public String createCourse(@RequestParam("name") String name, @RequestParam("teacher") Long teacher,
Это еще что такое? в параметр метода надо передавать либо Course либо CourseDto, а не этот список

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
> +        modelMap.addAttribute("time", courseService.getCourseById(id).getDeadline().toString().split(" ")[0]);
.toString().split(" ")[0] думаю стоит избавиться от этого
Пусть на фронте сами решают как им показывать дату дедлайна,  мне кажется, неправильно, что форматирование на сервере происходит

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/controllers/CourseController.java
>          List<Course> courses = courseService.getAllCourses();
зачем вынос в отдельную переменную нужен?

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/entities/Course.java
>      private Teacher teacher;    //Преподаватель курса
в чем рофл что вы юзаете ломбок и ты генеришь методы доступа?
второе, даже если ты генеришь это методы, они должны быть после полей.
По код конвеншенс:
class Clazz {
// поля
...
// методы
}

2019-04-22 16:25 UTC, RobertGareev commented on src/main/java/ru/itis/entities/Course.java
>      private Teacher teacher;    //Преподаватель курса
(надо удалить методы доступа, если вы используете ломбок)

2019-04-22 16:28 UTC, RobertGareev requested changes

2019-04-22 16:28 UTC, RobertGareev commented on src/main/java/ru/itis/CourseApplication.java
> +@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
для чего написан этот эксклюд?

2019-04-22 16:28 UTC, RobertGareev commented on src/main/java/ru/itis/entities/Course.java
> +    public void setSection(String section) {
втф ты вообще что ли не понимаешь что делаешь?

2019-04-22 16:28 UTC, RobertGareev commented on src/main/java/ru/itis/entities/Course.java
> +    public Course(String name, String description, int year, Teacher teacher, int quota, boolean rating, Date deadline, String section) {
@AllArgsConstructor для чего у тебя написана?

2019-04-22 16:28 UTC, RobertGareev commented on src/main/java/ru/itis/services/FileService.java
> +        String filePath = "C:/files/" + name + "/" + orgName;
путь нужно задавать из проперти файла

2019-04-22 16:30 UTC, RobertGareev requested changes

2019-04-22 16:30 UTC, RobertGareev commented on src/main/java/ru/itis/entities/Course.java
> +    public String getDateToString(){
Этот метод не должен находиться в этом классе.
Этот метод больше похож на класс метод класса-утилиты. Вы ведь представление даты в таком формате не только у этого контроллера можете юзать.

2019-04-23 09:58 UTC, kiseru commented
У тебя конфликт. Сделай `rebase` на ветку `master`.

2019-04-24 16:04 UTC, merged